// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch_events.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBatchEvent = `-- name: CreateBatchEvent :one
INSERT INTO batch_events (batch_id, occurred_at, kind, title, description, details)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, batch_id, occurred_at, kind, title, description, details
`

type CreateBatchEventParams struct {
	BatchID     uuid.UUID          `json:"batch_id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Kind        EventKind          `json:"kind"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Details     []byte             `json:"details"`
}

func (q *Queries) CreateBatchEvent(ctx context.Context, arg CreateBatchEventParams) (BatchEvent, error) {
	row := q.db.QueryRow(ctx, createBatchEvent,
		arg.BatchID,
		arg.OccurredAt,
		arg.Kind,
		arg.Title,
		arg.Description,
		arg.Details,
	)
	var i BatchEvent
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.OccurredAt,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.Details,
	)
	return i, err
}

const listBatchEventsForBatch = `-- name: ListBatchEventsForBatch :many
SELECT id, batch_id, occurred_at, kind, title, description, details FROM batch_events
WHERE batch_id = $1
ORDER BY occurred_at ASC, id ASC
`

func (q *Queries) ListBatchEventsForBatch(ctx context.Context, batchID uuid.UUID) ([]BatchEvent, error) {
	rows, err := q.db.Query(ctx, listBatchEventsForBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchEvent{}
	for rows.Next() {
		var i BatchEvent
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.OccurredAt,
			&i.Kind,
			&i.Title,
			&i.Description,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
