// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batches.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBatch = `-- name: CreateBatch :one
INSERT INTO batches (brewer_id, recipe_id, recipe_revision_id, name, brew_type, stage, started_at, notes, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, brewer_id, recipe_id, recipe_revision_id, name, brew_type, stage, started_at, bottled_at, visibility, notes, created_at, updated_at
`

type CreateBatchParams struct {
	BrewerID         uuid.UUID          `json:"brewer_id"`
	RecipeID         uuid.NullUUID      `json:"recipe_id"`
	RecipeRevisionID uuid.NullUUID      `json:"recipe_revision_id"`
	Name             string             `json:"name"`
	BrewType         BrewType           `json:"brew_type"`
	Stage            BatchStage         `json:"stage"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	Notes            pgtype.Text        `json:"notes"`
	Visibility       Visibility         `json:"visibility"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, createBatch,
		arg.BrewerID,
		arg.RecipeID,
		arg.RecipeRevisionID,
		arg.Name,
		arg.BrewType,
		arg.Stage,
		arg.StartedAt,
		arg.Notes,
		arg.Visibility,
	)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.BrewerID,
		&i.RecipeID,
		&i.RecipeRevisionID,
		&i.Name,
		&i.BrewType,
		&i.Stage,
		&i.StartedAt,
		&i.BottledAt,
		&i.Visibility,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBatch = `-- name: DeleteBatch :execrows
DELETE FROM batches WHERE id = $1 AND brewer_id = $2
`

type DeleteBatchParams struct {
	ID       uuid.UUID `json:"id"`
	BrewerID uuid.UUID `json:"brewer_id"`
}

func (q *Queries) DeleteBatch(ctx context.Context, arg DeleteBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBatch, arg.ID, arg.BrewerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBatchForUser = `-- name: GetBatchForUser :one
SELECT id, brewer_id, recipe_id, recipe_revision_id, name, brew_type, stage, started_at, bottled_at, visibility, notes, created_at, updated_at FROM batches
WHERE id = $1 AND brewer_id = $2
`

type GetBatchForUserParams struct {
	ID       uuid.UUID `json:"id"`
	BrewerID uuid.UUID `json:"brewer_id"`
}

func (q *Queries) GetBatchForUser(ctx context.Context, arg GetBatchForUserParams) (Batch, error) {
	row := q.db.QueryRow(ctx, getBatchForUser, arg.ID, arg.BrewerID)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.BrewerID,
		&i.RecipeID,
		&i.RecipeRevisionID,
		&i.Name,
		&i.BrewType,
		&i.Stage,
		&i.StartedAt,
		&i.BottledAt,
		&i.Visibility,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBatchesForUser = `-- name: ListBatchesForUser :many
SELECT id, brewer_id, recipe_id, recipe_revision_id, name, brew_type, stage, started_at, bottled_at, visibility, notes, created_at, updated_at FROM batches
WHERE brewer_id = $1
ORDER BY COALESCE(started_at, created_at) DESC
LIMIT $2 OFFSET $3
`

type ListBatchesForUserParams struct {
	BrewerID uuid.UUID `json:"brewer_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListBatchesForUser(ctx context.Context, arg ListBatchesForUserParams) ([]Batch, error) {
	rows, err := q.db.Query(ctx, listBatchesForUser, arg.BrewerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Batch{}
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.ID,
			&i.BrewerID,
			&i.RecipeID,
			&i.RecipeRevisionID,
			&i.Name,
			&i.BrewType,
			&i.Stage,
			&i.StartedAt,
			&i.BottledAt,
			&i.Visibility,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatch = `-- name: UpdateBatch :one
UPDATE batches SET
  name       = COALESCE($1,       name),
  stage      = COALESCE($2,      stage),
  notes      = COALESCE($3,      notes),
  started_at = COALESCE($4, started_at),
  bottled_at = COALESCE($5, bottled_at),
  visibility = COALESCE($6, visibility),
  updated_at = now()
WHERE id = $7 AND brewer_id = $8
RETURNING id, brewer_id, recipe_id, recipe_revision_id, name, brew_type, stage, started_at, bottled_at, visibility, notes, created_at, updated_at
`

type UpdateBatchParams struct {
	Name       pgtype.Text        `json:"name"`
	Stage      NullBatchStage     `json:"stage"`
	Notes      pgtype.Text        `json:"notes"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	BottledAt  pgtype.Timestamptz `json:"bottled_at"`
	Visibility NullVisibility     `json:"visibility"`
	ID         uuid.UUID          `json:"id"`
	BrewerID   uuid.UUID          `json:"brewer_id"`
}

func (q *Queries) UpdateBatch(ctx context.Context, arg UpdateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, updateBatch,
		arg.Name,
		arg.Stage,
		arg.Notes,
		arg.StartedAt,
		arg.BottledAt,
		arg.Visibility,
		arg.ID,
		arg.BrewerID,
	)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.BrewerID,
		&i.RecipeID,
		&i.RecipeRevisionID,
		&i.Name,
		&i.BrewType,
		&i.Stage,
		&i.StartedAt,
		&i.BottledAt,
		&i.Visibility,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
