// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_change.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailChangeRequest = `-- name: CreateEmailChangeRequest :one
INSERT INTO email_change_requests (
    user_id, new_email, old_email, confirm_token_hash, cancel_token_hash, expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, new_email, old_email, confirm_token_hash, cancel_token_hash, created_at, expires_at
`

type CreateEmailChangeRequestParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	NewEmail         string             `json:"new_email"`
	OldEmail         string             `json:"old_email"`
	ConfirmTokenHash string             `json:"confirm_token_hash"`
	CancelTokenHash  string             `json:"cancel_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailChangeRequest(ctx context.Context, arg CreateEmailChangeRequestParams) (EmailChangeRequest, error) {
	row := q.db.QueryRow(ctx, createEmailChangeRequest,
		arg.UserID,
		arg.NewEmail,
		arg.OldEmail,
		arg.ConfirmTokenHash,
		arg.CancelTokenHash,
		arg.ExpiresAt,
	)
	var i EmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.OldEmail,
		&i.ConfirmTokenHash,
		&i.CancelTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteEmailChangeRequest = `-- name: DeleteEmailChangeRequest :exec
DELETE FROM email_change_requests WHERE id = $1
`

func (q *Queries) DeleteEmailChangeRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailChangeRequest, id)
	return err
}

const deleteEmailChangeRequestsForUser = `-- name: DeleteEmailChangeRequestsForUser :exec
DELETE FROM email_change_requests WHERE user_id = $1
`

// DeleteEmailChangeRequestsForUser clears any pending requests for a user.
// Called before inserting a fresh request (one active change at a time) and
// as part of account anonymization.
func (q *Queries) DeleteEmailChangeRequestsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailChangeRequestsForUser, userID)
	return err
}

const deleteExpiredEmailChangeRequests = `-- name: DeleteExpiredEmailChangeRequests :exec
DELETE FROM email_change_requests WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredEmailChangeRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredEmailChangeRequests)
	return err
}

const getEmailChangeRequestByCancelHash = `-- name: GetEmailChangeRequestByCancelHash :one
SELECT id, user_id, new_email, old_email, confirm_token_hash, cancel_token_hash, created_at, expires_at FROM email_change_requests
WHERE cancel_token_hash = $1 AND expires_at > now()
`

// GetEmailChangeRequestByCancelHash returns a still-valid (unexpired) pending
// request matching the cancel-token hash.
func (q *Queries) GetEmailChangeRequestByCancelHash(ctx context.Context, cancelTokenHash string) (EmailChangeRequest, error) {
	row := q.db.QueryRow(ctx, getEmailChangeRequestByCancelHash, cancelTokenHash)
	var i EmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.OldEmail,
		&i.ConfirmTokenHash,
		&i.CancelTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getEmailChangeRequestByConfirmHash = `-- name: GetEmailChangeRequestByConfirmHash :one
SELECT id, user_id, new_email, old_email, confirm_token_hash, cancel_token_hash, created_at, expires_at FROM email_change_requests
WHERE confirm_token_hash = $1 AND expires_at > now()
`

// GetEmailChangeRequestByConfirmHash returns a still-valid (unexpired)
// pending request matching the confirm-token hash. Expired rows are treated
// as absent so a stale link can't be replayed.
func (q *Queries) GetEmailChangeRequestByConfirmHash(ctx context.Context, confirmTokenHash string) (EmailChangeRequest, error) {
	row := q.db.QueryRow(ctx, getEmailChangeRequestByConfirmHash, confirmTokenHash)
	var i EmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.OldEmail,
		&i.ConfirmTokenHash,
		&i.CancelTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
