// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingAdminBackups = `-- name: ClaimPendingAdminBackups :many
UPDATE admin_backups SET status = 'running'
WHERE id IN (
  SELECT id FROM admin_backups WHERE status = 'pending'
  ORDER BY created_at
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, status, file_path, size_bytes, storage_backend, error, created_at, completed_at
`

func (q *Queries) ClaimPendingAdminBackups(ctx context.Context) ([]AdminBackup, error) {
	rows, err := q.db.Query(ctx, claimPendingAdminBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminBackup{}
	for rows.Next() {
		var i AdminBackup
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.FilePath,
			&i.SizeBytes,
			&i.StorageBackend,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimPendingUserExports = `-- name: ClaimPendingUserExports :many
UPDATE user_exports SET status = 'running'
WHERE id IN (
  SELECT id FROM user_exports WHERE status = 'pending'
  ORDER BY created_at
  LIMIT 5
  FOR UPDATE SKIP LOCKED
)
RETURNING id, user_id, status, file_path, size_bytes, error, created_at, completed_at, expires_at
`

func (q *Queries) ClaimPendingUserExports(ctx context.Context) ([]UserExport, error) {
	rows, err := q.db.Query(ctx, claimPendingUserExports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserExport{}
	for rows.Next() {
		var i UserExport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.FilePath,
			&i.SizeBytes,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeAdminBackup = `-- name: CompleteAdminBackup :one
UPDATE admin_backups
SET status = 'complete', file_path = $2, size_bytes = $3, completed_at = now()
WHERE id = $1
RETURNING id, status, file_path, size_bytes, storage_backend, error, created_at, completed_at
`

type CompleteAdminBackupParams struct {
	ID        uuid.UUID   `json:"id"`
	FilePath  pgtype.Text `json:"file_path"`
	SizeBytes pgtype.Int8 `json:"size_bytes"`
}

func (q *Queries) CompleteAdminBackup(ctx context.Context, arg CompleteAdminBackupParams) (AdminBackup, error) {
	row := q.db.QueryRow(ctx, completeAdminBackup, arg.ID, arg.FilePath, arg.SizeBytes)
	var i AdminBackup
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FilePath,
		&i.SizeBytes,
		&i.StorageBackend,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeUserExport = `-- name: CompleteUserExport :one
UPDATE user_exports
SET status = 'complete', file_path = $2, size_bytes = $3,
    completed_at = now(), expires_at = now() + interval '7 days'
WHERE id = $1
RETURNING id, user_id, status, file_path, size_bytes, error, created_at, completed_at, expires_at
`

type CompleteUserExportParams struct {
	ID        uuid.UUID   `json:"id"`
	FilePath  pgtype.Text `json:"file_path"`
	SizeBytes pgtype.Int8 `json:"size_bytes"`
}

func (q *Queries) CompleteUserExport(ctx context.Context, arg CompleteUserExportParams) (UserExport, error) {
	row := q.db.QueryRow(ctx, completeUserExport, arg.ID, arg.FilePath, arg.SizeBytes)
	var i UserExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.FilePath,
		&i.SizeBytes,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createAdminBackup = `-- name: CreateAdminBackup :one

INSERT INTO admin_backups (status, storage_backend) VALUES ('pending', $1) RETURNING id, status, file_path, size_bytes, storage_backend, error, created_at, completed_at
`

// =============================================================================
// Admin backups
// =============================================================================
func (q *Queries) CreateAdminBackup(ctx context.Context, storageBackend string) (AdminBackup, error) {
	row := q.db.QueryRow(ctx, createAdminBackup, storageBackend)
	var i AdminBackup
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FilePath,
		&i.SizeBytes,
		&i.StorageBackend,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createUserExport = `-- name: CreateUserExport :one

INSERT INTO user_exports (user_id, status) VALUES ($1, 'pending') RETURNING id, user_id, status, file_path, size_bytes, error, created_at, completed_at, expires_at
`

// =============================================================================
// User exports
// =============================================================================
func (q *Queries) CreateUserExport(ctx context.Context, userID uuid.UUID) (UserExport, error) {
	row := q.db.QueryRow(ctx, createUserExport, userID)
	var i UserExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.FilePath,
		&i.SizeBytes,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredAdminBackups = `-- name: DeleteExpiredAdminBackups :many
DELETE FROM admin_backups
WHERE completed_at < now() - ($1::int * interval '1 day')
  AND status IN ('complete', 'failed')
RETURNING file_path
`

func (q *Queries) DeleteExpiredAdminBackups(ctx context.Context, dollar_1 int32) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, deleteExpiredAdminBackups, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var file_path pgtype.Text
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserExportsForUser = `-- name: DeleteUserExportsForUser :exec
DELETE FROM user_exports WHERE user_id = $1
`

func (q *Queries) DeleteUserExportsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserExportsForUser, userID)
	return err
}

const expireUserExports = `-- name: ExpireUserExports :many
UPDATE user_exports SET status = 'expired'
WHERE expires_at < now() AND status = 'complete'
RETURNING file_path
`

func (q *Queries) ExpireUserExports(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, expireUserExports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var file_path pgtype.Text
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failAdminBackup = `-- name: FailAdminBackup :exec
UPDATE admin_backups SET status = 'failed', error = $2, completed_at = now()
WHERE id = $1
`

type FailAdminBackupParams struct {
	ID    uuid.UUID   `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) FailAdminBackup(ctx context.Context, arg FailAdminBackupParams) error {
	_, err := q.db.Exec(ctx, failAdminBackup, arg.ID, arg.Error)
	return err
}

const failUserExport = `-- name: FailUserExport :exec
UPDATE user_exports SET status = 'failed', error = $2, completed_at = now()
WHERE id = $1
`

type FailUserExportParams struct {
	ID    uuid.UUID   `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) FailUserExport(ctx context.Context, arg FailUserExportParams) error {
	_, err := q.db.Exec(ctx, failUserExport, arg.ID, arg.Error)
	return err
}

const getAdminBackup = `-- name: GetAdminBackup :one
SELECT id, status, file_path, size_bytes, storage_backend, error, created_at, completed_at FROM admin_backups WHERE id = $1
`

func (q *Queries) GetAdminBackup(ctx context.Context, id uuid.UUID) (AdminBackup, error) {
	row := q.db.QueryRow(ctx, getAdminBackup, id)
	var i AdminBackup
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FilePath,
		&i.SizeBytes,
		&i.StorageBackend,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPendingUserExport = `-- name: GetPendingUserExport :one
SELECT id, user_id, status, file_path, size_bytes, error, created_at, completed_at, expires_at FROM user_exports
WHERE user_id = $1 AND status IN ('pending', 'running')
LIMIT 1
`

func (q *Queries) GetPendingUserExport(ctx context.Context, userID uuid.UUID) (UserExport, error) {
	row := q.db.QueryRow(ctx, getPendingUserExport, userID)
	var i UserExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.FilePath,
		&i.SizeBytes,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserExport = `-- name: GetUserExport :one
SELECT id, user_id, status, file_path, size_bytes, error, created_at, completed_at, expires_at FROM user_exports WHERE id = $1 AND user_id = $2
`

type GetUserExportParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserExport(ctx context.Context, arg GetUserExportParams) (UserExport, error) {
	row := q.db.QueryRow(ctx, getUserExport, arg.ID, arg.UserID)
	var i UserExport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.FilePath,
		&i.SizeBytes,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAdminBackups = `-- name: ListAdminBackups :many
SELECT id, status, file_path, size_bytes, storage_backend, error, created_at, completed_at FROM admin_backups ORDER BY created_at DESC LIMIT 20
`

func (q *Queries) ListAdminBackups(ctx context.Context) ([]AdminBackup, error) {
	rows, err := q.db.Query(ctx, listAdminBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminBackup{}
	for rows.Next() {
		var i AdminBackup
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.FilePath,
			&i.SizeBytes,
			&i.StorageBackend,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowsByUser = `-- name: ListFollowsByUser :many

SELECT follower_id, followed_id, created_at FROM follows WHERE follower_id = $1 ORDER BY created_at ASC
`

// =============================================================================
// Social data for export
// =============================================================================
func (q *Queries) ListFollowsByUser(ctx context.Context, followerID uuid.UUID) ([]Follow, error) {
	rows, err := q.db.Query(ctx, listFollowsByUser, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Follow{}
	for rows.Next() {
		var i Follow
		if err := rows.Scan(&i.FollowerID, &i.FollowedID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikesByUser = `-- name: ListLikesByUser :many
SELECT user_id, recipe_id, created_at FROM recipe_likes WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListLikesByUser(ctx context.Context, userID uuid.UUID) ([]RecipeLike, error) {
	rows, err := q.db.Query(ctx, listLikesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeLike{}
	for rows.Next() {
		var i RecipeLike
		if err := rows.Scan(&i.UserID, &i.RecipeID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeCommentsByUser = `-- name: ListRecipeCommentsByUser :many
SELECT id, recipe_id, author_id, body, created_at FROM recipe_comments WHERE author_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListRecipeCommentsByUser(ctx context.Context, authorID uuid.UUID) ([]RecipeComment, error) {
	rows, err := q.db.Query(ctx, listRecipeCommentsByUser, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeComment{}
	for rows.Next() {
		var i RecipeComment
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserExportFilePathsForUser = `-- name: ListUserExportFilePathsForUser :many
SELECT file_path FROM user_exports
WHERE user_id = $1 AND file_path IS NOT NULL
`

func (q *Queries) ListUserExportFilePathsForUser(ctx context.Context, userID uuid.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listUserExportFilePathsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var file_path pgtype.Text
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserExports = `-- name: ListUserExports :many
SELECT id, user_id, status, file_path, size_bytes, error, created_at, completed_at, expires_at FROM user_exports WHERE user_id = $1 ORDER BY created_at DESC LIMIT 20
`

func (q *Queries) ListUserExports(ctx context.Context, userID uuid.UUID) ([]UserExport, error) {
	rows, err := q.db.Query(ctx, listUserExports, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserExport{}
	for rows.Next() {
		var i UserExport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.FilePath,
			&i.SizeBytes,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
