// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (user_id, kind, name, amount, unit, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, kind, name, amount, unit, notes, created_at, updated_at
`

type CreateInventoryItemParams struct {
	UserID uuid.UUID      `json:"user_id"`
	Kind   IngredientKind `json:"kind"`
	Name   string         `json:"name"`
	Amount pgtype.Numeric `json:"amount"`
	Unit   pgtype.Text    `json:"unit"`
	Notes  pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.UserID,
		arg.Kind,
		arg.Name,
		arg.Amount,
		arg.Unit,
		arg.Notes,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllInventoryForUser = `-- name: DeleteAllInventoryForUser :exec
DELETE FROM inventory_items WHERE user_id = $1
`

// Used by account anonymization to wipe inventory alongside other
// per-user data. Returns nothing — caller doesn't care about the count.
func (q *Queries) DeleteAllInventoryForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllInventoryForUser, userID)
	return err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :execrows
DELETE FROM inventory_items WHERE id = $1 AND user_id = $2
`

type DeleteInventoryItemParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteInventoryItem(ctx context.Context, arg DeleteInventoryItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInventoryItem, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInventoryItemForUser = `-- name: GetInventoryItemForUser :one
SELECT id, user_id, kind, name, amount, unit, notes, created_at, updated_at FROM inventory_items WHERE id = $1 AND user_id = $2
`

type GetInventoryItemForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetInventoryItemForUser(ctx context.Context, arg GetInventoryItemForUserParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, getInventoryItemForUser, arg.ID, arg.UserID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInventoryForUser = `-- name: ListInventoryForUser :many
SELECT id, user_id, kind, name, amount, unit, notes, created_at, updated_at FROM inventory_items
WHERE user_id = $1
ORDER BY kind ASC, lower(name) ASC, created_at ASC
`

// Inventory is bounded (a brewer keeps tens, not thousands of items),
// so plain ORDER BY without keyset pagination is fine for v1. Sort by
// kind first then name so the page reads as a categorized list.
func (q *Queries) ListInventoryForUser(ctx context.Context, userID uuid.UUID) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, listInventoryForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryItem{}
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Name,
			&i.Amount,
			&i.Unit,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchInventoryForRecipe = `-- name: MatchInventoryForRecipe :many
SELECT
  ri.id            AS ingredient_id,
  ri.kind          AS ingredient_kind,
  ri.name          AS ingredient_name,
  ri.amount        AS ingredient_amount,
  ri.unit          AS ingredient_unit,
  inv.id           AS inventory_id,
  inv.amount       AS inventory_amount,
  inv.unit         AS inventory_unit,
  -- Separately surface the "name matches but unit doesn't" case so the
  -- UI can flag a unit mismatch instead of silently calling it missing.
  EXISTS (
    SELECT 1 FROM inventory_items inv2
    WHERE inv2.user_id = $1
      AND inv2.kind = ri.kind
      AND lower(inv2.name) = lower(ri.name)
      AND inv2.unit IS DISTINCT FROM ri.unit
  ) AS has_unit_mismatch
FROM recipe_ingredients ri
LEFT JOIN inventory_items inv
  ON inv.user_id = $1
 AND inv.kind = ri.kind
 AND lower(inv.name) = lower(ri.name)
 AND inv.unit IS NOT DISTINCT FROM ri.unit
WHERE ri.recipe_id = $2
ORDER BY ri.sort_order ASC, ri.id ASC
`

type MatchInventoryForRecipeParams struct {
	UserID   uuid.UUID `json:"user_id"`
	RecipeID uuid.UUID `json:"recipe_id"`
}

type MatchInventoryForRecipeRow struct {
	IngredientID     uuid.UUID      `json:"ingredient_id"`
	IngredientKind   IngredientKind `json:"ingredient_kind"`
	IngredientName   string         `json:"ingredient_name"`
	IngredientAmount pgtype.Numeric `json:"ingredient_amount"`
	IngredientUnit   pgtype.Text    `json:"ingredient_unit"`
	InventoryID      uuid.NullUUID  `json:"inventory_id"`
	InventoryAmount  pgtype.Numeric `json:"inventory_amount"`
	InventoryUnit    pgtype.Text    `json:"inventory_unit"`
	HasUnitMismatch  bool           `json:"has_unit_mismatch"`
}

// Returns one row per recipe ingredient with the matching inventory
// item joined in (NULL inventory cols mean "missing"). Match is strict:
// same kind, case-insensitive name, same unit (or both NULL). Unit
// conversion is deferred — the handler reports a "unit mismatch" hint
// separately when names match but units don't.
func (q *Queries) MatchInventoryForRecipe(ctx context.Context, arg MatchInventoryForRecipeParams) ([]MatchInventoryForRecipeRow, error) {
	rows, err := q.db.Query(ctx, matchInventoryForRecipe, arg.UserID, arg.RecipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchInventoryForRecipeRow{}
	for rows.Next() {
		var i MatchInventoryForRecipeRow
		if err := rows.Scan(
			&i.IngredientID,
			&i.IngredientKind,
			&i.IngredientName,
			&i.IngredientAmount,
			&i.IngredientUnit,
			&i.InventoryID,
			&i.InventoryAmount,
			&i.InventoryUnit,
			&i.HasUnitMismatch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryItem = `-- name: UpdateInventoryItem :one
UPDATE inventory_items SET
  kind       = COALESCE($1,       kind),
  name       = COALESCE($2,       name),
  amount     = COALESCE($3,     amount),
  unit       = COALESCE($4,       unit),
  notes      = COALESCE($5,      notes),
  updated_at = now()
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, kind, name, amount, unit, notes, created_at, updated_at
`

type UpdateInventoryItemParams struct {
	Kind   NullIngredientKind `json:"kind"`
	Name   pgtype.Text        `json:"name"`
	Amount pgtype.Numeric     `json:"amount"`
	Unit   pgtype.Text        `json:"unit"`
	Notes  pgtype.Text        `json:"notes"`
	ID     uuid.UUID          `json:"id"`
	UserID uuid.UUID          `json:"user_id"`
}

// COALESCE PATCH semantics — omitted columns retain their value. amount
// and unit can't be cleared to NULL via PATCH (matches the rest of the
// API). notes can be cleared via empty string.
func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, updateInventoryItem,
		arg.Kind,
		arg.Name,
		arg.Amount,
		arg.Unit,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
