// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BatchStage string

const (
	BatchStagePlanning  BatchStage = "planning"
	BatchStagePrimary   BatchStage = "primary"
	BatchStageSecondary BatchStage = "secondary"
	BatchStageAging     BatchStage = "aging"
	BatchStageBottled   BatchStage = "bottled"
	BatchStageArchived  BatchStage = "archived"
)

func (e *BatchStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BatchStage(s)
	case string:
		*e = BatchStage(s)
	default:
		return fmt.Errorf("unsupported scan type for BatchStage: %T", src)
	}
	return nil
}

type NullBatchStage struct {
	BatchStage BatchStage `json:"batch_stage"`
	Valid      bool       `json:"valid"` // Valid is true if BatchStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBatchStage) Scan(value interface{}) error {
	if value == nil {
		ns.BatchStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BatchStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBatchStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BatchStage), nil
}

type BrewType string

const (
	BrewTypeMead     BrewType = "mead"
	BrewTypeBeer     BrewType = "beer"
	BrewTypeCider    BrewType = "cider"
	BrewTypeWine     BrewType = "wine"
	BrewTypeKombucha BrewType = "kombucha"
)

func (e *BrewType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BrewType(s)
	case string:
		*e = BrewType(s)
	default:
		return fmt.Errorf("unsupported scan type for BrewType: %T", src)
	}
	return nil
}

type NullBrewType struct {
	BrewType BrewType `json:"brew_type"`
	Valid    bool     `json:"valid"` // Valid is true if BrewType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBrewType) Scan(value interface{}) error {
	if value == nil {
		ns.BrewType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BrewType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBrewType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BrewType), nil
}

type EventKind string

const (
	EventKindPitch            EventKind = "pitch"
	EventKindNutrientAddition EventKind = "nutrient_addition"
	EventKindDegas            EventKind = "degas"
	EventKindRack             EventKind = "rack"
	EventKindAddition         EventKind = "addition"
	EventKindStabilize        EventKind = "stabilize"
	EventKindBacksweeten      EventKind = "backsweeten"
	EventKindBottle           EventKind = "bottle"
	EventKindPhoto            EventKind = "photo"
	EventKindNote             EventKind = "note"
	EventKindOther            EventKind = "other"
)

func (e *EventKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventKind(s)
	case string:
		*e = EventKind(s)
	default:
		return fmt.Errorf("unsupported scan type for EventKind: %T", src)
	}
	return nil
}

type NullEventKind struct {
	EventKind EventKind `json:"event_kind"`
	Valid     bool      `json:"valid"` // Valid is true if EventKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventKind) Scan(value interface{}) error {
	if value == nil {
		ns.EventKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventKind), nil
}

type IngredientKind string

const (
	IngredientKindHoney    IngredientKind = "honey"
	IngredientKindWater    IngredientKind = "water"
	IngredientKindYeast    IngredientKind = "yeast"
	IngredientKindNutrient IngredientKind = "nutrient"
	IngredientKindFruit    IngredientKind = "fruit"
	IngredientKindSpice    IngredientKind = "spice"
	IngredientKindOak      IngredientKind = "oak"
	IngredientKindAcid     IngredientKind = "acid"
	IngredientKindTannin   IngredientKind = "tannin"
	IngredientKindOther    IngredientKind = "other"
)

func (e *IngredientKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IngredientKind(s)
	case string:
		*e = IngredientKind(s)
	default:
		return fmt.Errorf("unsupported scan type for IngredientKind: %T", src)
	}
	return nil
}

type NullIngredientKind struct {
	IngredientKind IngredientKind `json:"ingredient_kind"`
	Valid          bool           `json:"valid"` // Valid is true if IngredientKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIngredientKind) Scan(value interface{}) error {
	if value == nil {
		ns.IngredientKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IngredientKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIngredientKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IngredientKind), nil
}

type JobStatus string

const (
	JobStatusPending  JobStatus = "pending"
	JobStatusRunning  JobStatus = "running"
	JobStatusComplete JobStatus = "complete"
	JobStatusFailed   JobStatus = "failed"
	JobStatusExpired  JobStatus = "expired"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type ReminderAnchor string

const (
	ReminderAnchorAbsolute    ReminderAnchor = "absolute"
	ReminderAnchorBatchStart  ReminderAnchor = "batch_start"
	ReminderAnchorPitch       ReminderAnchor = "pitch"
	ReminderAnchorRack        ReminderAnchor = "rack"
	ReminderAnchorBottle      ReminderAnchor = "bottle"
	ReminderAnchorCustomEvent ReminderAnchor = "custom_event"
)

func (e *ReminderAnchor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReminderAnchor(s)
	case string:
		*e = ReminderAnchor(s)
	default:
		return fmt.Errorf("unsupported scan type for ReminderAnchor: %T", src)
	}
	return nil
}

type NullReminderAnchor struct {
	ReminderAnchor ReminderAnchor `json:"reminder_anchor"`
	Valid          bool           `json:"valid"` // Valid is true if ReminderAnchor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReminderAnchor) Scan(value interface{}) error {
	if value == nil {
		ns.ReminderAnchor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReminderAnchor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReminderAnchor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReminderAnchor), nil
}

type ReminderStatus string

const (
	ReminderStatusScheduled ReminderStatus = "scheduled"
	ReminderStatusFired     ReminderStatus = "fired"
	ReminderStatusCompleted ReminderStatus = "completed"
	ReminderStatusSnoozed   ReminderStatus = "snoozed"
	ReminderStatusDismissed ReminderStatus = "dismissed"
	ReminderStatusCancelled ReminderStatus = "cancelled"
)

func (e *ReminderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReminderStatus(s)
	case string:
		*e = ReminderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReminderStatus: %T", src)
	}
	return nil
}

type NullReminderStatus struct {
	ReminderStatus ReminderStatus `json:"reminder_status"`
	Valid          bool           `json:"valid"` // Valid is true if ReminderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReminderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReminderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReminderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReminderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReminderStatus), nil
}

type Visibility string

const (
	VisibilityPublic   Visibility = "public"
	VisibilityUnlisted Visibility = "unlisted"
	VisibilityPrivate  Visibility = "private"
)

func (e *Visibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Visibility(s)
	case string:
		*e = Visibility(s)
	default:
		return fmt.Errorf("unsupported scan type for Visibility: %T", src)
	}
	return nil
}

type NullVisibility struct {
	Visibility Visibility `json:"visibility"`
	Valid      bool       `json:"valid"` // Valid is true if Visibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.Visibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Visibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Visibility), nil
}

type AdminAuditLog struct {
	ID         uuid.UUID          `json:"id"`
	AdminID    uuid.UUID          `json:"admin_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   uuid.UUID          `json:"target_id"`
	Reason     pgtype.Text        `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AdminBackup struct {
	ID             uuid.UUID          `json:"id"`
	Status         JobStatus          `json:"status"`
	FilePath       pgtype.Text        `json:"file_path"`
	SizeBytes      pgtype.Int8        `json:"size_bytes"`
	StorageBackend string             `json:"storage_backend"`
	Error          pgtype.Text        `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type Batch struct {
	ID               uuid.UUID          `json:"id"`
	BrewerID         uuid.UUID          `json:"brewer_id"`
	RecipeID         uuid.NullUUID      `json:"recipe_id"`
	RecipeRevisionID uuid.NullUUID      `json:"recipe_revision_id"`
	Name             string             `json:"name"`
	BrewType         BrewType           `json:"brew_type"`
	Stage            BatchStage         `json:"stage"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	BottledAt        pgtype.Timestamptz `json:"bottled_at"`
	Visibility       Visibility         `json:"visibility"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type BatchComment struct {
	ID        uuid.UUID          `json:"id"`
	BatchID   uuid.UUID          `json:"batch_id"`
	AuthorID  uuid.UUID          `json:"author_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BatchDevice struct {
	ID                uuid.UUID          `json:"id"`
	BatchID           uuid.UUID          `json:"batch_id"`
	DeviceID          uuid.UUID          `json:"device_id"`
	AttachedAt        pgtype.Timestamptz `json:"attached_at"`
	DetachedAt        pgtype.Timestamptz `json:"detached_at"`
	GravityOffset     pgtype.Numeric     `json:"gravity_offset"`
	TemperatureOffset pgtype.Numeric     `json:"temperature_offset"`
	Paused            bool               `json:"paused"`
}

type BatchEvent struct {
	ID          uuid.UUID          `json:"id"`
	BatchID     uuid.UUID          `json:"batch_id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Kind        EventKind          `json:"kind"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Details     []byte             `json:"details"`
}

type BatchEventMedium struct {
	ID        uuid.UUID   `json:"id"`
	EventID   uuid.UUID   `json:"event_id"`
	Url       string      `json:"url"`
	Caption   pgtype.Text `json:"caption"`
	SortOrder int32       `json:"sort_order"`
}

type BatchIngredient struct {
	ID        uuid.UUID      `json:"id"`
	BatchID   uuid.UUID      `json:"batch_id"`
	Kind      IngredientKind `json:"kind"`
	Name      string         `json:"name"`
	Amount    pgtype.Numeric `json:"amount"`
	Unit      pgtype.Text    `json:"unit"`
	SortOrder int32          `json:"sort_order"`
	Details   []byte         `json:"details"`
}

type Device struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Type         string             `json:"type"`
	Config       []byte             `json:"config"`
	WebhookToken pgtype.Text        `json:"webhook_token"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
}

type Follow struct {
	FollowerID uuid.UUID          `json:"follower_id"`
	FollowedID uuid.UUID          `json:"followed_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	ReminderID uuid.NullUUID      `json:"reminder_id"`
	Kind       string             `json:"kind"`
	Title      string             `json:"title"`
	Body       pgtype.Text        `json:"body"`
	UrlPath    pgtype.Text        `json:"url_path"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type NotificationPref struct {
	UserID          uuid.UUID   `json:"user_id"`
	PushEnabled     bool        `json:"push_enabled"`
	EmailEnabled    bool        `json:"email_enabled"`
	QuietHoursStart pgtype.Time `json:"quiet_hours_start"`
	QuietHoursEnd   pgtype.Time `json:"quiet_hours_end"`
	Timezone        string      `json:"timezone"`
}

type PushDevice struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Platform   string             `json:"platform"`
	Token      string             `json:"token"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type Reading struct {
	ID           uuid.UUID          `json:"id"`
	BatchID      uuid.UUID          `json:"batch_id"`
	DeviceID     uuid.NullUUID      `json:"device_id"`
	TakenAt      pgtype.Timestamptz `json:"taken_at"`
	Gravity      pgtype.Numeric     `json:"gravity"`
	TemperatureC pgtype.Numeric     `json:"temperature_c"`
	Ph           pgtype.Numeric     `json:"ph"`
	Notes        pgtype.Text        `json:"notes"`
	Source       string             `json:"source"`
	RawPayload   []byte             `json:"raw_payload"`
}

type Recipe struct {
	ID                uuid.UUID          `json:"id"`
	AuthorID          uuid.UUID          `json:"author_id"`
	ParentID          uuid.NullUUID      `json:"parent_id"`
	ParentRevisionID  uuid.NullUUID      `json:"parent_revision_id"`
	CurrentRevisionID uuid.NullUUID      `json:"current_revision_id"`
	RevisionCount     int32              `json:"revision_count"`
	ForkCount         int32              `json:"fork_count"`
	BrewType          BrewType           `json:"brew_type"`
	Style             pgtype.Text        `json:"style"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	TargetOg          pgtype.Numeric     `json:"target_og"`
	TargetFg          pgtype.Numeric     `json:"target_fg"`
	TargetAbv         pgtype.Numeric     `json:"target_abv"`
	BatchSizeL        pgtype.Numeric     `json:"batch_size_l"`
	Visibility        Visibility         `json:"visibility"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RecipeComment struct {
	ID        uuid.UUID          `json:"id"`
	RecipeID  uuid.UUID          `json:"recipe_id"`
	AuthorID  uuid.UUID          `json:"author_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RecipeIngredient struct {
	ID        uuid.UUID      `json:"id"`
	RecipeID  uuid.UUID      `json:"recipe_id"`
	Kind      IngredientKind `json:"kind"`
	Name      string         `json:"name"`
	Amount    pgtype.Numeric `json:"amount"`
	Unit      pgtype.Text    `json:"unit"`
	SortOrder int32          `json:"sort_order"`
	Details   []byte         `json:"details"`
}

type RecipeLike struct {
	UserID    uuid.UUID          `json:"user_id"`
	RecipeID  uuid.UUID          `json:"recipe_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RecipeRating struct {
	UserID    uuid.UUID          `json:"user_id"`
	RecipeID  uuid.UUID          `json:"recipe_id"`
	Rating    int16              `json:"rating"`
	Review    pgtype.Text        `json:"review"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RecipeReminderTemplate struct {
	ID                 uuid.UUID      `json:"id"`
	RecipeID           uuid.UUID      `json:"recipe_id"`
	Title              string         `json:"title"`
	Description        pgtype.Text    `json:"description"`
	Anchor             ReminderAnchor `json:"anchor"`
	OffsetMinutes      int32          `json:"offset_minutes"`
	SuggestedEventKind NullEventKind  `json:"suggested_event_kind"`
	SortOrder          int32          `json:"sort_order"`
}

type RecipeRevision struct {
	ID             uuid.UUID          `json:"id"`
	RecipeID       uuid.UUID          `json:"recipe_id"`
	RevisionNumber int32              `json:"revision_number"`
	AuthorID       uuid.UUID          `json:"author_id"`
	Message        pgtype.Text        `json:"message"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Style          pgtype.Text        `json:"style"`
	TargetOg       pgtype.Numeric     `json:"target_og"`
	TargetFg       pgtype.Numeric     `json:"target_fg"`
	TargetAbv      pgtype.Numeric     `json:"target_abv"`
	BatchSizeL     pgtype.Numeric     `json:"batch_size_l"`
	Ingredients    []byte             `json:"ingredients"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID                 uuid.UUID          `json:"id"`
	BatchID            uuid.NullUUID      `json:"batch_id"`
	UserID             uuid.UUID          `json:"user_id"`
	TemplateID         uuid.NullUUID      `json:"template_id"`
	Title              string             `json:"title"`
	Description        pgtype.Text        `json:"description"`
	FireAt             pgtype.Timestamptz `json:"fire_at"`
	Rrule              pgtype.Text        `json:"rrule"`
	Status             ReminderStatus     `json:"status"`
	FiredAt            pgtype.Timestamptz `json:"fired_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	SuggestedEventKind NullEventKind      `json:"suggested_event_kind"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Ip         *netip.Addr        `json:"ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type TastingNote struct {
	ID        uuid.UUID          `json:"id"`
	BatchID   uuid.UUID          `json:"batch_id"`
	AuthorID  uuid.UUID          `json:"author_id"`
	TastedAt  pgtype.Timestamptz `json:"tasted_at"`
	Rating    pgtype.Int2        `json:"rating"`
	Aroma     pgtype.Text        `json:"aroma"`
	Flavor    pgtype.Text        `json:"flavor"`
	Mouthfeel pgtype.Text        `json:"mouthfeel"`
	Finish    pgtype.Text        `json:"finish"`
	Notes     pgtype.Text        `json:"notes"`
}

type User struct {
	ID                   uuid.UUID          `json:"id"`
	Username             string             `json:"username"`
	Email                string             `json:"email"`
	DisplayName          pgtype.Text        `json:"display_name"`
	Bio                  pgtype.Text        `json:"bio"`
	AvatarUrl            pgtype.Text        `json:"avatar_url"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	DeletionScheduledFor pgtype.Timestamptz `json:"deletion_scheduled_for"`
	DeletionChoices      []byte             `json:"deletion_choices"`
	DeletionReason       pgtype.Text        `json:"deletion_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	PasswordHash         pgtype.Text        `json:"password_hash"`
}

type UserExport struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Status      JobStatus          `json:"status"`
	FilePath    pgtype.Text        `json:"file_path"`
	SizeBytes   pgtype.Int8        `json:"size_bytes"`
	Error       pgtype.Text        `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type UserImport struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Status         JobStatus          `json:"status"`
	SourceFilename pgtype.Text        `json:"source_filename"`
	Summary        []byte             `json:"summary"`
	Error          pgtype.Text        `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}
