// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, reminder_id, kind, title, body, url_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, reminder_id, kind, title, body, url_path, read_at, created_at
`

type CreateNotificationParams struct {
	UserID     uuid.UUID     `json:"user_id"`
	ReminderID uuid.NullUUID `json:"reminder_id"`
	Kind       string        `json:"kind"`
	Title      string        `json:"title"`
	Body       pgtype.Text   `json:"body"`
	UrlPath    pgtype.Text   `json:"url_path"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.ReminderID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.UrlPath,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReminderID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.UrlPath,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationPrefs = `-- name: GetNotificationPrefs :one
SELECT user_id, push_enabled, email_enabled, quiet_hours_start, quiet_hours_end, timezone FROM notification_prefs WHERE user_id = $1
`

func (q *Queries) GetNotificationPrefs(ctx context.Context, userID uuid.UUID) (NotificationPref, error) {
	row := q.db.QueryRow(ctx, getNotificationPrefs, userID)
	var i NotificationPref
	err := row.Scan(
		&i.UserID,
		&i.PushEnabled,
		&i.EmailEnabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.Timezone,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, reminder_id, kind, title, body, url_path, read_at, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReminderID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.UrlPath,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = now()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertNotificationPrefs = `-- name: UpsertNotificationPrefs :one
INSERT INTO notification_prefs (user_id, push_enabled, email_enabled, quiet_hours_start, quiet_hours_end, timezone)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
  push_enabled      = EXCLUDED.push_enabled,
  email_enabled     = EXCLUDED.email_enabled,
  quiet_hours_start = EXCLUDED.quiet_hours_start,
  quiet_hours_end   = EXCLUDED.quiet_hours_end,
  timezone          = EXCLUDED.timezone
RETURNING user_id, push_enabled, email_enabled, quiet_hours_start, quiet_hours_end, timezone
`

type UpsertNotificationPrefsParams struct {
	UserID          uuid.UUID   `json:"user_id"`
	PushEnabled     bool        `json:"push_enabled"`
	EmailEnabled    bool        `json:"email_enabled"`
	QuietHoursStart pgtype.Time `json:"quiet_hours_start"`
	QuietHoursEnd   pgtype.Time `json:"quiet_hours_end"`
	Timezone        string      `json:"timezone"`
}

func (q *Queries) UpsertNotificationPrefs(ctx context.Context, arg UpsertNotificationPrefsParams) (NotificationPref, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPrefs,
		arg.UserID,
		arg.PushEnabled,
		arg.EmailEnabled,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
		arg.Timezone,
	)
	var i NotificationPref
	err := row.Scan(
		&i.UserID,
		&i.PushEnabled,
		&i.EmailEnabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.Timezone,
	)
	return i, err
}
