// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_devices.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushDevice = `-- name: DeletePushDevice :execrows
DELETE FROM push_devices WHERE user_id = $1 AND token = $2
`

type DeletePushDeviceParams struct {
	UserID uuid.UUID `json:"user_id"`
	Token  string    `json:"token"`
}

func (q *Queries) DeletePushDevice(ctx context.Context, arg DeletePushDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushDevice, arg.UserID, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePushDevicesForUser = `-- name: DeletePushDevicesForUser :exec
DELETE FROM push_devices WHERE user_id = $1
`

func (q *Queries) DeletePushDevicesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePushDevicesForUser, userID)
	return err
}

const listPushDevicesForUser = `-- name: ListPushDevicesForUser :many
SELECT id, user_id, platform, token, last_seen_at, p256dh, auth FROM push_devices WHERE user_id = $1
`

func (q *Queries) ListPushDevicesForUser(ctx context.Context, userID uuid.UUID) ([]PushDevice, error) {
	rows, err := q.db.Query(ctx, listPushDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushDevice{}
	for rows.Next() {
		var i PushDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Token,
			&i.LastSeenAt,
			&i.P256dh,
			&i.Auth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushDevice = `-- name: UpsertPushDevice :one
INSERT INTO push_devices (user_id, platform, token, p256dh, auth, last_seen_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id, token) DO UPDATE SET
  last_seen_at = now(),
  p256dh       = EXCLUDED.p256dh,
  auth         = EXCLUDED.auth
RETURNING id, user_id, platform, token, last_seen_at, p256dh, auth
`

type UpsertPushDeviceParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	Platform string      `json:"platform"`
	Token    string      `json:"token"`
	P256dh   pgtype.Text `json:"p256dh"`
	Auth     pgtype.Text `json:"auth"`
}

func (q *Queries) UpsertPushDevice(ctx context.Context, arg UpsertPushDeviceParams) (PushDevice, error) {
	row := q.db.QueryRow(ctx, upsertPushDevice,
		arg.UserID,
		arg.Platform,
		arg.Token,
		arg.P256dh,
		arg.Auth,
	)
	var i PushDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Token,
		&i.LastSeenAt,
		&i.P256dh,
		&i.Auth,
	)
	return i, err
}
