// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error
	GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserCredentialByEmail(ctx context.Context, email string) (GetUserCredentialByEmailRow, error)
	GetUserCredentialByUsername(ctx context.Context, username string) (GetUserCredentialByUsernameRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	TouchSession(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
