// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createForkedRecipe = `-- name: CreateForkedRecipe :one
INSERT INTO recipes (author_id, parent_id, parent_revision_id, brew_type, name, style, description, target_og, target_fg, target_abv, batch_size_l, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, author_id, parent_id, parent_revision_id, current_revision_id, revision_count, fork_count, brew_type, style, name, description, target_og, target_fg, target_abv, batch_size_l, visibility, created_at, updated_at
`

type CreateForkedRecipeParams struct {
	AuthorID         uuid.UUID      `json:"author_id"`
	ParentID         uuid.NullUUID  `json:"parent_id"`
	ParentRevisionID uuid.NullUUID  `json:"parent_revision_id"`
	BrewType         BrewType       `json:"brew_type"`
	Name             string         `json:"name"`
	Style            pgtype.Text    `json:"style"`
	Description      pgtype.Text    `json:"description"`
	TargetOg         pgtype.Numeric `json:"target_og"`
	TargetFg         pgtype.Numeric `json:"target_fg"`
	TargetAbv        pgtype.Numeric `json:"target_abv"`
	BatchSizeL       pgtype.Numeric `json:"batch_size_l"`
	Visibility       Visibility     `json:"visibility"`
}

func (q *Queries) CreateForkedRecipe(ctx context.Context, arg CreateForkedRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createForkedRecipe,
		arg.AuthorID,
		arg.ParentID,
		arg.ParentRevisionID,
		arg.BrewType,
		arg.Name,
		arg.Style,
		arg.Description,
		arg.TargetOg,
		arg.TargetFg,
		arg.TargetAbv,
		arg.BatchSizeL,
		arg.Visibility,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ParentID,
		&i.ParentRevisionID,
		&i.CurrentRevisionID,
		&i.RevisionCount,
		&i.ForkCount,
		&i.BrewType,
		&i.Style,
		&i.Name,
		&i.Description,
		&i.TargetOg,
		&i.TargetFg,
		&i.TargetAbv,
		&i.BatchSizeL,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecipeComment = `-- name: CreateRecipeComment :one
INSERT INTO recipe_comments (recipe_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, recipe_id, author_id, body, created_at
`

type CreateRecipeCommentParams struct {
	RecipeID uuid.UUID `json:"recipe_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Body     string    `json:"body"`
}

func (q *Queries) CreateRecipeComment(ctx context.Context, arg CreateRecipeCommentParams) (RecipeComment, error) {
	row := q.db.QueryRow(ctx, createRecipeComment, arg.RecipeID, arg.AuthorID, arg.Body)
	var i RecipeComment
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createRecipeDraft = `-- name: CreateRecipeDraft :one
INSERT INTO recipes (author_id, brew_type, name, style, description, target_og, target_fg, target_abv, batch_size_l, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, author_id, parent_id, parent_revision_id, current_revision_id, revision_count, fork_count, brew_type, style, name, description, target_og, target_fg, target_abv, batch_size_l, visibility, created_at, updated_at
`

type CreateRecipeDraftParams struct {
	AuthorID    uuid.UUID      `json:"author_id"`
	BrewType    BrewType       `json:"brew_type"`
	Name        string         `json:"name"`
	Style       pgtype.Text    `json:"style"`
	Description pgtype.Text    `json:"description"`
	TargetOg    pgtype.Numeric `json:"target_og"`
	TargetFg    pgtype.Numeric `json:"target_fg"`
	TargetAbv   pgtype.Numeric `json:"target_abv"`
	BatchSizeL  pgtype.Numeric `json:"batch_size_l"`
	Visibility  Visibility     `json:"visibility"`
}

func (q *Queries) CreateRecipeDraft(ctx context.Context, arg CreateRecipeDraftParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipeDraft,
		arg.AuthorID,
		arg.BrewType,
		arg.Name,
		arg.Style,
		arg.Description,
		arg.TargetOg,
		arg.TargetFg,
		arg.TargetAbv,
		arg.BatchSizeL,
		arg.Visibility,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ParentID,
		&i.ParentRevisionID,
		&i.CurrentRevisionID,
		&i.RevisionCount,
		&i.ForkCount,
		&i.BrewType,
		&i.Style,
		&i.Name,
		&i.Description,
		&i.TargetOg,
		&i.TargetFg,
		&i.TargetAbv,
		&i.BatchSizeL,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecipeIngredient = `-- name: CreateRecipeIngredient :one
INSERT INTO recipe_ingredients (recipe_id, kind, name, amount, unit, sort_order, details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, recipe_id, kind, name, amount, unit, sort_order, details
`

type CreateRecipeIngredientParams struct {
	RecipeID  uuid.UUID      `json:"recipe_id"`
	Kind      IngredientKind `json:"kind"`
	Name      string         `json:"name"`
	Amount    pgtype.Numeric `json:"amount"`
	Unit      pgtype.Text    `json:"unit"`
	SortOrder int32          `json:"sort_order"`
	Details   []byte         `json:"details"`
}

func (q *Queries) CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error) {
	row := q.db.QueryRow(ctx, createRecipeIngredient,
		arg.RecipeID,
		arg.Kind,
		arg.Name,
		arg.Amount,
		arg.Unit,
		arg.SortOrder,
		arg.Details,
	)
	var i RecipeIngredient
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Kind,
		&i.Name,
		&i.Amount,
		&i.Unit,
		&i.SortOrder,
		&i.Details,
	)
	return i, err
}

const createRecipeRevision = `-- name: CreateRecipeRevision :one
INSERT INTO recipe_revisions (recipe_id, revision_number, author_id, message, name, style, description, target_og, target_fg, target_abv, batch_size_l, ingredients)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, recipe_id, revision_number, author_id, message, name, description, style, target_og, target_fg, target_abv, batch_size_l, ingredients, created_at
`

type CreateRecipeRevisionParams struct {
	RecipeID       uuid.UUID      `json:"recipe_id"`
	RevisionNumber int32          `json:"revision_number"`
	AuthorID       uuid.UUID      `json:"author_id"`
	Message        pgtype.Text    `json:"message"`
	Name           string         `json:"name"`
	Style          pgtype.Text    `json:"style"`
	Description    pgtype.Text    `json:"description"`
	TargetOg       pgtype.Numeric `json:"target_og"`
	TargetFg       pgtype.Numeric `json:"target_fg"`
	TargetAbv      pgtype.Numeric `json:"target_abv"`
	BatchSizeL     pgtype.Numeric `json:"batch_size_l"`
	Ingredients    []byte         `json:"ingredients"`
}

func (q *Queries) CreateRecipeRevision(ctx context.Context, arg CreateRecipeRevisionParams) (RecipeRevision, error) {
	row := q.db.QueryRow(ctx, createRecipeRevision,
		arg.RecipeID,
		arg.RevisionNumber,
		arg.AuthorID,
		arg.Message,
		arg.Name,
		arg.Style,
		arg.Description,
		arg.TargetOg,
		arg.TargetFg,
		arg.TargetAbv,
		arg.BatchSizeL,
		arg.Ingredients,
	)
	var i RecipeRevision
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.RevisionNumber,
		&i.AuthorID,
		&i.Message,
		&i.Name,
		&i.Description,
		&i.Style,
		&i.TargetOg,
		&i.TargetFg,
		&i.TargetAbv,
		&i.BatchSizeL,
		&i.Ingredients,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :execrows
DELETE FROM recipes WHERE id = $1 AND author_id = $2
`

type DeleteRecipeParams struct {
	ID       uuid.UUID `json:"id"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) DeleteRecipe(ctx context.Context, arg DeleteRecipeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecipe, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecipeComment = `-- name: DeleteRecipeComment :execrows
DELETE FROM recipe_comments WHERE id = $1 AND author_id = $2
`

type DeleteRecipeCommentParams struct {
	ID       uuid.UUID `json:"id"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) DeleteRecipeComment(ctx context.Context, arg DeleteRecipeCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecipeComment, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecipeIngredients = `-- name: DeleteRecipeIngredients :exec
DELETE FROM recipe_ingredients WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeIngredients(ctx context.Context, recipeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecipeIngredients, recipeID)
	return err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, author_id, parent_id, parent_revision_id, current_revision_id, revision_count, fork_count, brew_type, style, name, description, target_og, target_fg, target_abv, batch_size_l, visibility, created_at, updated_at FROM recipes WHERE id = $1
`

func (q *Queries) GetRecipeByID(ctx context.Context, id uuid.UUID) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ParentID,
		&i.ParentRevisionID,
		&i.CurrentRevisionID,
		&i.RevisionCount,
		&i.ForkCount,
		&i.BrewType,
		&i.Style,
		&i.Name,
		&i.Description,
		&i.TargetOg,
		&i.TargetFg,
		&i.TargetAbv,
		&i.BatchSizeL,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeRevisionByNumber = `-- name: GetRecipeRevisionByNumber :one
SELECT id, recipe_id, revision_number, author_id, message, name, description, style, target_og, target_fg, target_abv, batch_size_l, ingredients, created_at FROM recipe_revisions
WHERE recipe_id = $1 AND revision_number = $2
`

type GetRecipeRevisionByNumberParams struct {
	RecipeID       uuid.UUID `json:"recipe_id"`
	RevisionNumber int32     `json:"revision_number"`
}

func (q *Queries) GetRecipeRevisionByNumber(ctx context.Context, arg GetRecipeRevisionByNumberParams) (RecipeRevision, error) {
	row := q.db.QueryRow(ctx, getRecipeRevisionByNumber, arg.RecipeID, arg.RevisionNumber)
	var i RecipeRevision
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.RevisionNumber,
		&i.AuthorID,
		&i.Message,
		&i.Name,
		&i.Description,
		&i.Style,
		&i.TargetOg,
		&i.TargetFg,
		&i.TargetAbv,
		&i.BatchSizeL,
		&i.Ingredients,
		&i.CreatedAt,
	)
	return i, err
}

const getRevisionByID = `-- name: GetRevisionByID :one
SELECT id, recipe_id, revision_number, author_id, message, name, description, style, target_og, target_fg, target_abv, batch_size_l, ingredients, created_at FROM recipe_revisions WHERE id = $1
`

func (q *Queries) GetRevisionByID(ctx context.Context, id uuid.UUID) (RecipeRevision, error) {
	row := q.db.QueryRow(ctx, getRevisionByID, id)
	var i RecipeRevision
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.RevisionNumber,
		&i.AuthorID,
		&i.Message,
		&i.Name,
		&i.Description,
		&i.Style,
		&i.TargetOg,
		&i.TargetFg,
		&i.TargetAbv,
		&i.BatchSizeL,
		&i.Ingredients,
		&i.CreatedAt,
	)
	return i, err
}

const incrementForkCount = `-- name: IncrementForkCount :exec
UPDATE recipes SET fork_count = fork_count + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) IncrementForkCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementForkCount, id)
	return err
}

const likeRecipe = `-- name: LikeRecipe :exec
INSERT INTO recipe_likes (user_id, recipe_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LikeRecipeParams struct {
	UserID   uuid.UUID `json:"user_id"`
	RecipeID uuid.UUID `json:"recipe_id"`
}

func (q *Queries) LikeRecipe(ctx context.Context, arg LikeRecipeParams) error {
	_, err := q.db.Exec(ctx, likeRecipe, arg.UserID, arg.RecipeID)
	return err
}

const listAllRecipesForAuthor = `-- name: ListAllRecipesForAuthor :many
SELECT id, author_id, parent_id, parent_revision_id, current_revision_id, revision_count, fork_count, brew_type, style, name, description, target_og, target_fg, target_abv, batch_size_l, visibility, created_at, updated_at FROM recipes WHERE author_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListAllRecipesForAuthor(ctx context.Context, authorID uuid.UUID) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listAllRecipesForAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ParentID,
			&i.ParentRevisionID,
			&i.CurrentRevisionID,
			&i.RevisionCount,
			&i.ForkCount,
			&i.BrewType,
			&i.Style,
			&i.Name,
			&i.Description,
			&i.TargetOg,
			&i.TargetFg,
			&i.TargetAbv,
			&i.BatchSizeL,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicRecipes = `-- name: ListPublicRecipes :many
SELECT id, author_id, parent_id, parent_revision_id, current_revision_id, revision_count, fork_count, brew_type, style, name, description, target_og, target_fg, target_abv, batch_size_l, visibility, created_at, updated_at FROM recipes
WHERE visibility = 'public'
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicRecipesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublicRecipes(ctx context.Context, arg ListPublicRecipesParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listPublicRecipes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ParentID,
			&i.ParentRevisionID,
			&i.CurrentRevisionID,
			&i.RevisionCount,
			&i.ForkCount,
			&i.BrewType,
			&i.Style,
			&i.Name,
			&i.Description,
			&i.TargetOg,
			&i.TargetFg,
			&i.TargetAbv,
			&i.BatchSizeL,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeComments = `-- name: ListRecipeComments :many
SELECT
  rc.id, rc.recipe_id, rc.author_id, rc.body, rc.created_at,
  u.username AS author_username
FROM recipe_comments rc
JOIN users u ON u.id = rc.author_id
WHERE rc.recipe_id = $1
ORDER BY rc.created_at ASC
LIMIT $2 OFFSET $3
`

type ListRecipeCommentsParams struct {
	RecipeID uuid.UUID `json:"recipe_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListRecipeCommentsRow struct {
	ID             uuid.UUID          `json:"id"`
	RecipeID       uuid.UUID          `json:"recipe_id"`
	AuthorID       uuid.UUID          `json:"author_id"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AuthorUsername string             `json:"author_username"`
}

func (q *Queries) ListRecipeComments(ctx context.Context, arg ListRecipeCommentsParams) ([]ListRecipeCommentsRow, error) {
	rows, err := q.db.Query(ctx, listRecipeComments, arg.RecipeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipeCommentsRow{}
	for rows.Next() {
		var i ListRecipeCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
SELECT id, recipe_id, kind, name, amount, unit, sort_order, details FROM recipe_ingredients
WHERE recipe_id = $1
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListRecipeIngredients(ctx context.Context, recipeID uuid.UUID) ([]RecipeIngredient, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeIngredient{}
	for rows.Next() {
		var i RecipeIngredient
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Kind,
			&i.Name,
			&i.Amount,
			&i.Unit,
			&i.SortOrder,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeRevisions = `-- name: ListRecipeRevisions :many
SELECT id, recipe_id, revision_number, author_id, message, name, description, style, target_og, target_fg, target_abv, batch_size_l, ingredients, created_at FROM recipe_revisions
WHERE recipe_id = $1
ORDER BY revision_number DESC
`

func (q *Queries) ListRecipeRevisions(ctx context.Context, recipeID uuid.UUID) ([]RecipeRevision, error) {
	rows, err := q.db.Query(ctx, listRecipeRevisions, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeRevision{}
	for rows.Next() {
		var i RecipeRevision
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.RevisionNumber,
			&i.AuthorID,
			&i.Message,
			&i.Name,
			&i.Description,
			&i.Style,
			&i.TargetOg,
			&i.TargetFg,
			&i.TargetAbv,
			&i.BatchSizeL,
			&i.Ingredients,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesForAuthor = `-- name: ListRecipesForAuthor :many
SELECT id, author_id, parent_id, parent_revision_id, current_revision_id, revision_count, fork_count, brew_type, style, name, description, target_og, target_fg, target_abv, batch_size_l, visibility, created_at, updated_at FROM recipes
WHERE author_id = $1
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListRecipesForAuthorParams struct {
	AuthorID uuid.UUID `json:"author_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListRecipesForAuthor(ctx context.Context, arg ListRecipesForAuthorParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listRecipesForAuthor, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ParentID,
			&i.ParentRevisionID,
			&i.CurrentRevisionID,
			&i.RevisionCount,
			&i.ForkCount,
			&i.BrewType,
			&i.Style,
			&i.Name,
			&i.Description,
			&i.TargetOg,
			&i.TargetFg,
			&i.TargetAbv,
			&i.BatchSizeL,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecipeRevision = `-- name: SetRecipeRevision :one
UPDATE recipes
SET current_revision_id = $2,
    revision_count      = revision_count + 1,
    updated_at          = now()
WHERE id = $1
RETURNING id, author_id, parent_id, parent_revision_id, current_revision_id, revision_count, fork_count, brew_type, style, name, description, target_og, target_fg, target_abv, batch_size_l, visibility, created_at, updated_at
`

type SetRecipeRevisionParams struct {
	ID                uuid.UUID     `json:"id"`
	CurrentRevisionID uuid.NullUUID `json:"current_revision_id"`
}

func (q *Queries) SetRecipeRevision(ctx context.Context, arg SetRecipeRevisionParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, setRecipeRevision, arg.ID, arg.CurrentRevisionID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ParentID,
		&i.ParentRevisionID,
		&i.CurrentRevisionID,
		&i.RevisionCount,
		&i.ForkCount,
		&i.BrewType,
		&i.Style,
		&i.Name,
		&i.Description,
		&i.TargetOg,
		&i.TargetFg,
		&i.TargetAbv,
		&i.BatchSizeL,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlikeRecipe = `-- name: UnlikeRecipe :exec
DELETE FROM recipe_likes WHERE user_id = $1 AND recipe_id = $2
`

type UnlikeRecipeParams struct {
	UserID   uuid.UUID `json:"user_id"`
	RecipeID uuid.UUID `json:"recipe_id"`
}

func (q *Queries) UnlikeRecipe(ctx context.Context, arg UnlikeRecipeParams) error {
	_, err := q.db.Exec(ctx, unlikeRecipe, arg.UserID, arg.RecipeID)
	return err
}

const updateRecipeMeta = `-- name: UpdateRecipeMeta :one
UPDATE recipes SET
  name         = COALESCE($1,         name),
  style        = COALESCE($2,        style),
  description  = COALESCE($3,  description),
  target_og    = COALESCE($4,    target_og),
  target_fg    = COALESCE($5,    target_fg),
  target_abv   = COALESCE($6,   target_abv),
  batch_size_l = COALESCE($7, batch_size_l),
  visibility   = COALESCE($8,   visibility),
  updated_at   = now()
WHERE id = $9 AND author_id = $10
RETURNING id, author_id, parent_id, parent_revision_id, current_revision_id, revision_count, fork_count, brew_type, style, name, description, target_og, target_fg, target_abv, batch_size_l, visibility, created_at, updated_at
`

type UpdateRecipeMetaParams struct {
	Name        pgtype.Text    `json:"name"`
	Style       pgtype.Text    `json:"style"`
	Description pgtype.Text    `json:"description"`
	TargetOg    pgtype.Numeric `json:"target_og"`
	TargetFg    pgtype.Numeric `json:"target_fg"`
	TargetAbv   pgtype.Numeric `json:"target_abv"`
	BatchSizeL  pgtype.Numeric `json:"batch_size_l"`
	Visibility  NullVisibility `json:"visibility"`
	ID          uuid.UUID      `json:"id"`
	AuthorID    uuid.UUID      `json:"author_id"`
}

func (q *Queries) UpdateRecipeMeta(ctx context.Context, arg UpdateRecipeMetaParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipeMeta,
		arg.Name,
		arg.Style,
		arg.Description,
		arg.TargetOg,
		arg.TargetFg,
		arg.TargetAbv,
		arg.BatchSizeL,
		arg.Visibility,
		arg.ID,
		arg.AuthorID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ParentID,
		&i.ParentRevisionID,
		&i.CurrentRevisionID,
		&i.RevisionCount,
		&i.ForkCount,
		&i.BrewType,
		&i.Style,
		&i.Name,
		&i.Description,
		&i.TargetOg,
		&i.TargetFg,
		&i.TargetAbv,
		&i.BatchSizeL,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
