// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelReminder = `-- name: CancelReminder :execrows
UPDATE reminders SET status = 'cancelled'
WHERE id = $1 AND user_id = $2 AND status NOT IN ('fired', 'completed')
`

type CancelReminderParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CancelReminder(ctx context.Context, arg CancelReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelReminder, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDueReminders = `-- name: ClaimDueReminders :many
UPDATE reminders
SET status = 'fired', fired_at = now()
WHERE id IN (
  SELECT id FROM reminders
  WHERE status = 'scheduled' AND fire_at <= now()
  ORDER BY fire_at
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, batch_id, user_id, template_id, title, description, fire_at, rrule, status, fired_at, completed_at, suggested_event_kind, created_at
`

func (q *Queries) ClaimDueReminders(ctx context.Context, limit int32) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, claimDueReminders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.UserID,
			&i.TemplateID,
			&i.Title,
			&i.Description,
			&i.FireAt,
			&i.Rrule,
			&i.Status,
			&i.FiredAt,
			&i.CompletedAt,
			&i.SuggestedEventKind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (batch_id, user_id, title, description, fire_at, suggested_event_kind)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, batch_id, user_id, template_id, title, description, fire_at, rrule, status, fired_at, completed_at, suggested_event_kind, created_at
`

type CreateReminderParams struct {
	BatchID            uuid.NullUUID      `json:"batch_id"`
	UserID             uuid.UUID          `json:"user_id"`
	Title              string             `json:"title"`
	Description        pgtype.Text        `json:"description"`
	FireAt             pgtype.Timestamptz `json:"fire_at"`
	SuggestedEventKind NullEventKind      `json:"suggested_event_kind"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.BatchID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.FireAt,
		arg.SuggestedEventKind,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.UserID,
		&i.TemplateID,
		&i.Title,
		&i.Description,
		&i.FireAt,
		&i.Rrule,
		&i.Status,
		&i.FiredAt,
		&i.CompletedAt,
		&i.SuggestedEventKind,
		&i.CreatedAt,
	)
	return i, err
}

const getReminder = `-- name: GetReminder :one
SELECT id, batch_id, user_id, template_id, title, description, fire_at, rrule, status, fired_at, completed_at, suggested_event_kind, created_at FROM reminders WHERE id = $1 AND user_id = $2
`

type GetReminderParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetReminder(ctx context.Context, arg GetReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, getReminder, arg.ID, arg.UserID)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.UserID,
		&i.TemplateID,
		&i.Title,
		&i.Description,
		&i.FireAt,
		&i.Rrule,
		&i.Status,
		&i.FiredAt,
		&i.CompletedAt,
		&i.SuggestedEventKind,
		&i.CreatedAt,
	)
	return i, err
}

const listBatchReminders = `-- name: ListBatchReminders :many
SELECT id, batch_id, user_id, template_id, title, description, fire_at, rrule, status, fired_at, completed_at, suggested_event_kind, created_at FROM reminders
WHERE batch_id = $1 AND user_id = $2
ORDER BY fire_at ASC
`

type ListBatchRemindersParams struct {
	BatchID uuid.NullUUID `json:"batch_id"`
	UserID  uuid.UUID     `json:"user_id"`
}

func (q *Queries) ListBatchReminders(ctx context.Context, arg ListBatchRemindersParams) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listBatchReminders, arg.BatchID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.UserID,
			&i.TemplateID,
			&i.Title,
			&i.Description,
			&i.FireAt,
			&i.Rrule,
			&i.Status,
			&i.FiredAt,
			&i.CompletedAt,
			&i.SuggestedEventKind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReminder = `-- name: UpdateReminder :one
UPDATE reminders SET
  title                = COALESCE($1,                title),
  description          = COALESCE($2,          description),
  fire_at              = COALESCE($3,              fire_at),
  status               = COALESCE($4,               status),
  suggested_event_kind = COALESCE($5, suggested_event_kind)
WHERE id = $6 AND user_id = $7
RETURNING id, batch_id, user_id, template_id, title, description, fire_at, rrule, status, fired_at, completed_at, suggested_event_kind, created_at
`

type UpdateReminderParams struct {
	Title              pgtype.Text        `json:"title"`
	Description        pgtype.Text        `json:"description"`
	FireAt             pgtype.Timestamptz `json:"fire_at"`
	Status             NullReminderStatus `json:"status"`
	SuggestedEventKind NullEventKind      `json:"suggested_event_kind"`
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
}

func (q *Queries) UpdateReminder(ctx context.Context, arg UpdateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, updateReminder,
		arg.Title,
		arg.Description,
		arg.FireAt,
		arg.Status,
		arg.SuggestedEventKind,
		arg.ID,
		arg.UserID,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.UserID,
		&i.TemplateID,
		&i.Title,
		&i.Description,
		&i.FireAt,
		&i.Rrule,
		&i.Status,
		&i.FiredAt,
		&i.CompletedAt,
		&i.SuggestedEventKind,
		&i.CreatedAt,
	)
	return i, err
}
