// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminder_templates.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReminderTemplate = `-- name: CreateReminderTemplate :one
INSERT INTO recipe_reminder_templates (recipe_id, title, description, anchor, offset_minutes, suggested_event_kind, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, recipe_id, title, description, anchor, offset_minutes, suggested_event_kind, sort_order
`

type CreateReminderTemplateParams struct {
	RecipeID           uuid.UUID      `json:"recipe_id"`
	Title              string         `json:"title"`
	Description        pgtype.Text    `json:"description"`
	Anchor             ReminderAnchor `json:"anchor"`
	OffsetMinutes      int32          `json:"offset_minutes"`
	SuggestedEventKind NullEventKind  `json:"suggested_event_kind"`
	SortOrder          int32          `json:"sort_order"`
}

func (q *Queries) CreateReminderTemplate(ctx context.Context, arg CreateReminderTemplateParams) (RecipeReminderTemplate, error) {
	row := q.db.QueryRow(ctx, createReminderTemplate,
		arg.RecipeID,
		arg.Title,
		arg.Description,
		arg.Anchor,
		arg.OffsetMinutes,
		arg.SuggestedEventKind,
		arg.SortOrder,
	)
	var i RecipeReminderTemplate
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Title,
		&i.Description,
		&i.Anchor,
		&i.OffsetMinutes,
		&i.SuggestedEventKind,
		&i.SortOrder,
	)
	return i, err
}

const deleteReminderTemplate = `-- name: DeleteReminderTemplate :execrows
DELETE FROM recipe_reminder_templates WHERE id = $1 AND recipe_id = $2
`

type DeleteReminderTemplateParams struct {
	ID       uuid.UUID `json:"id"`
	RecipeID uuid.UUID `json:"recipe_id"`
}

func (q *Queries) DeleteReminderTemplate(ctx context.Context, arg DeleteReminderTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReminderTemplate, arg.ID, arg.RecipeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReminderTemplate = `-- name: GetReminderTemplate :one
SELECT id, recipe_id, title, description, anchor, offset_minutes, suggested_event_kind, sort_order FROM recipe_reminder_templates WHERE id = $1
`

func (q *Queries) GetReminderTemplate(ctx context.Context, id uuid.UUID) (RecipeReminderTemplate, error) {
	row := q.db.QueryRow(ctx, getReminderTemplate, id)
	var i RecipeReminderTemplate
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Title,
		&i.Description,
		&i.Anchor,
		&i.OffsetMinutes,
		&i.SuggestedEventKind,
		&i.SortOrder,
	)
	return i, err
}

const listReminderTemplates = `-- name: ListReminderTemplates :many
SELECT id, recipe_id, title, description, anchor, offset_minutes, suggested_event_kind, sort_order FROM recipe_reminder_templates
WHERE recipe_id = $1
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListReminderTemplates(ctx context.Context, recipeID uuid.UUID) ([]RecipeReminderTemplate, error) {
	rows, err := q.db.Query(ctx, listReminderTemplates, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeReminderTemplate{}
	for rows.Next() {
		var i RecipeReminderTemplate
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Title,
			&i.Description,
			&i.Anchor,
			&i.OffsetMinutes,
			&i.SuggestedEventKind,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materializeReminderTemplates = `-- name: MaterializeReminderTemplates :exec
INSERT INTO reminders (batch_id, user_id, template_id, title, description, fire_at, suggested_event_kind)
SELECT
  $1::uuid,
  $2::uuid,
  t.id,
  t.title,
  t.description,
  $3::timestamptz + (t.offset_minutes * INTERVAL '1 minute'),
  t.suggested_event_kind
FROM recipe_reminder_templates t
WHERE t.recipe_id = $4::uuid
  AND t.anchor = $5::reminder_anchor
  AND NOT EXISTS (
    SELECT 1 FROM reminders r
    WHERE r.template_id = t.id
      AND r.batch_id = $1::uuid
      AND r.status NOT IN ('cancelled', 'dismissed')
  )
`

type MaterializeReminderTemplatesParams struct {
	BatchID    uuid.UUID          `json:"batch_id"`
	UserID     uuid.UUID          `json:"user_id"`
	AnchorTime pgtype.Timestamptz `json:"anchor_time"`
	RecipeID   uuid.UUID          `json:"recipe_id"`
	Anchor     ReminderAnchor     `json:"anchor"`
}

func (q *Queries) MaterializeReminderTemplates(ctx context.Context, arg MaterializeReminderTemplatesParams) error {
	_, err := q.db.Exec(ctx, materializeReminderTemplates,
		arg.BatchID,
		arg.UserID,
		arg.AnchorTime,
		arg.RecipeID,
		arg.Anchor,
	)
	return err
}

const updateReminderTemplate = `-- name: UpdateReminderTemplate :one
UPDATE recipe_reminder_templates SET
  title                = COALESCE($1,                title),
  description          = COALESCE($2,          description),
  anchor               = COALESCE($3,               anchor),
  offset_minutes       = COALESCE($4,       offset_minutes),
  suggested_event_kind = COALESCE($5, suggested_event_kind),
  sort_order           = COALESCE($6,           sort_order)
WHERE id = $7 AND recipe_id = $8
RETURNING id, recipe_id, title, description, anchor, offset_minutes, suggested_event_kind, sort_order
`

type UpdateReminderTemplateParams struct {
	Title              pgtype.Text        `json:"title"`
	Description        pgtype.Text        `json:"description"`
	Anchor             NullReminderAnchor `json:"anchor"`
	OffsetMinutes      pgtype.Int4        `json:"offset_minutes"`
	SuggestedEventKind NullEventKind      `json:"suggested_event_kind"`
	SortOrder          pgtype.Int4        `json:"sort_order"`
	ID                 uuid.UUID          `json:"id"`
	RecipeID           uuid.UUID          `json:"recipe_id"`
}

func (q *Queries) UpdateReminderTemplate(ctx context.Context, arg UpdateReminderTemplateParams) (RecipeReminderTemplate, error) {
	row := q.db.QueryRow(ctx, updateReminderTemplate,
		arg.Title,
		arg.Description,
		arg.Anchor,
		arg.OffsetMinutes,
		arg.SuggestedEventKind,
		arg.SortOrder,
		arg.ID,
		arg.RecipeID,
	)
	var i RecipeReminderTemplate
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Title,
		&i.Description,
		&i.Anchor,
		&i.OffsetMinutes,
		&i.SuggestedEventKind,
		&i.SortOrder,
	)
	return i, err
}
