// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasting_notes.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTastingNote = `-- name: CreateTastingNote :one
INSERT INTO tasting_notes (batch_id, author_id, tasted_at, rating, aroma, flavor, mouthfeel, finish, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, batch_id, author_id, tasted_at, rating, aroma, flavor, mouthfeel, finish, notes
`

type CreateTastingNoteParams struct {
	BatchID   uuid.UUID          `json:"batch_id"`
	AuthorID  uuid.UUID          `json:"author_id"`
	TastedAt  pgtype.Timestamptz `json:"tasted_at"`
	Rating    pgtype.Int2        `json:"rating"`
	Aroma     pgtype.Text        `json:"aroma"`
	Flavor    pgtype.Text        `json:"flavor"`
	Mouthfeel pgtype.Text        `json:"mouthfeel"`
	Finish    pgtype.Text        `json:"finish"`
	Notes     pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateTastingNote(ctx context.Context, arg CreateTastingNoteParams) (TastingNote, error) {
	row := q.db.QueryRow(ctx, createTastingNote,
		arg.BatchID,
		arg.AuthorID,
		arg.TastedAt,
		arg.Rating,
		arg.Aroma,
		arg.Flavor,
		arg.Mouthfeel,
		arg.Finish,
		arg.Notes,
	)
	var i TastingNote
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.AuthorID,
		&i.TastedAt,
		&i.Rating,
		&i.Aroma,
		&i.Flavor,
		&i.Mouthfeel,
		&i.Finish,
		&i.Notes,
	)
	return i, err
}

const listTastingNotesForBatch = `-- name: ListTastingNotesForBatch :many
SELECT id, batch_id, author_id, tasted_at, rating, aroma, flavor, mouthfeel, finish, notes FROM tasting_notes
WHERE batch_id = $1
ORDER BY tasted_at DESC, id ASC
`

func (q *Queries) ListTastingNotesForBatch(ctx context.Context, batchID uuid.UUID) ([]TastingNote, error) {
	rows, err := q.db.Query(ctx, listTastingNotesForBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TastingNote{}
	for rows.Next() {
		var i TastingNote
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.AuthorID,
			&i.TastedAt,
			&i.Rating,
			&i.Aroma,
			&i.Flavor,
			&i.Mouthfeel,
			&i.Finish,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
