// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, display_name)
VALUES ($1, $2, $3)
RETURNING id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at, password_hash, is_admin
`

type CreateUserParams struct {
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.DeletionChoices,
		&i.DeletionReason,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (username, email, display_name, password_hash, is_admin)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at, password_hash, is_admin
`

type CreateUserWithPasswordParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	DisplayName  pgtype.Text `json:"display_name"`
	PasswordHash pgtype.Text `json:"password_hash"`
	IsAdmin      bool        `json:"is_admin"`
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.DeletionChoices,
		&i.DeletionReason,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at, password_hash, is_admin FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.DeletionChoices,
		&i.DeletionReason,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at, password_hash, is_admin FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.DeletionChoices,
		&i.DeletionReason,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at, password_hash, is_admin FROM users
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.DeletionChoices,
		&i.DeletionReason,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const getUserCredentialByEmail = `-- name: GetUserCredentialByEmail :one
SELECT id, username, email, password_hash FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserCredentialByEmailRow struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) GetUserCredentialByEmail(ctx context.Context, email string) (GetUserCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialByEmail, email)
	var i GetUserCredentialByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserCredentialByUsername = `-- name: GetUserCredentialByUsername :one
SELECT id, username, email, password_hash FROM users
WHERE username = $1 AND deleted_at IS NULL
`

type GetUserCredentialByUsernameRow struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) GetUserCredentialByUsername(ctx context.Context, username string) (GetUserCredentialByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserCredentialByUsername, username)
	var i GetUserCredentialByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at, password_hash, is_admin FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.DeletedAt,
			&i.DeletionScheduledFor,
			&i.DeletionChoices,
			&i.DeletionReason,
			&i.CreatedAt,
			&i.PasswordHash,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  display_name = COALESCE($1, display_name),
  bio          = COALESCE($2,          bio),
  avatar_url   = COALESCE($3,   avatar_url)
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at, password_hash, is_admin
`

type UpdateUserParams struct {
	DisplayName pgtype.Text `json:"display_name"`
	Bio         pgtype.Text `json:"bio"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.DeletionChoices,
		&i.DeletionReason,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.IsAdmin,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	PasswordHash pgtype.Text `json:"password_hash"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
