// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_prefs.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserPrefsForUser = `-- name: DeleteUserPrefsForUser :exec
DELETE FROM user_prefs WHERE user_id = $1
`

func (q *Queries) DeleteUserPrefsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserPrefsForUser, userID)
	return err
}

const getUserPrefs = `-- name: GetUserPrefs :one
SELECT user_id, degree_units, timezone FROM user_prefs WHERE user_id = $1
`

func (q *Queries) GetUserPrefs(ctx context.Context, userID uuid.UUID) (UserPref, error) {
	row := q.db.QueryRow(ctx, getUserPrefs, userID)
	var i UserPref
	err := row.Scan(&i.UserID, &i.DegreeUnits, &i.Timezone)
	return i, err
}

const upsertUserPrefs = `-- name: UpsertUserPrefs :one
INSERT INTO user_prefs (user_id, degree_units, timezone)
VALUES (
  $1,
  COALESCE($2, 'C'),
  COALESCE($3, 'UTC')
)
ON CONFLICT (user_id) DO UPDATE SET
  degree_units = COALESCE($2, user_prefs.degree_units),
  timezone     = COALESCE($3,     user_prefs.timezone)
RETURNING user_id, degree_units, timezone
`

type UpsertUserPrefsParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	DegreeUnits interface{} `json:"degree_units"`
	Timezone    interface{} `json:"timezone"`
}

// Upsert with partial overwrite: NULL values fall back to defaults on
// INSERT and to the existing value on UPDATE (COALESCE pattern matching
// the rest of the PATCH endpoints).
func (q *Queries) UpsertUserPrefs(ctx context.Context, arg UpsertUserPrefsParams) (UserPref, error) {
	row := q.db.QueryRow(ctx, upsertUserPrefs, arg.UserID, arg.DegreeUnits, arg.Timezone)
	var i UserPref
	err := row.Scan(&i.UserID, &i.DegreeUnits, &i.Timezone)
	return i, err
}
