// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, display_name)
VALUES ($1, $2, $3)
RETURNING id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at
`

type CreateUserParams struct {
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.DeletionChoices,
		&i.DeletionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.DeletionChoices,
		&i.DeletionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.DeletionChoices,
		&i.DeletionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at FROM users
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.DeletedAt,
		&i.DeletionScheduledFor,
		&i.DeletionChoices,
		&i.DeletionReason,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, display_name, bio, avatar_url, deleted_at, deletion_scheduled_for, deletion_choices, deletion_reason, created_at FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.DeletedAt,
			&i.DeletionScheduledFor,
			&i.DeletionChoices,
			&i.DeletionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
